import uuid from 'uuid-random';

export const mockproducts = [
  {
    id : uuid(),
    name : 'Manzana roja',
    price : 2000,
    per : 'kg',
    picture : '',
  },
  {
    id : uuid(),
    name : 'Manzana verde',
    price : 2500,
    per : 'kg',
    picture : '',
  },
  {
    id : uuid(),
    name : 'Cebolla cabezona',
    price : 3000,
    per : 'kg',
    picture : '',
  },
  {
    id : uuid(),
    name : 'Apio',
    price : 1700,
    per : 'lb',
    picture : '',
  },
]

export const mockusers = [
  {
    username : 'yosoydaniel@hotmail.com',
    password : '12345',
    fname : 'Daniel',
    lname : 'Castañeda',
    email : 'yosoydaniel@hotmail.com',
    phnumber : 3103334455,
    idtype : 'CC',
    idnumber : 123456789,
    money_bank : 'Bancolombia',
    money_acc_type : 'Ahorros',
    money_acc_number : 987654321,
  },
  {
    username : '3105552244',
    password : '12345',
    fname : 'Ana',
    lname : 'Mosquera',
    email : 'anamosq@hotmail.com',
    phnumber : 3105552244,
    idtype : 'CC',
    idnumber : 1122334455,
    money_bank : 'Nequi',
    money_acc_type : 'Ahorros',
    money_acc_number : 3105552244,
  },
  {
    username : 'pedroperez@gmail.com',
    password : 'pedro',
    fname : 'Pedro',
    lname : 'Pérez',
    email : 'pedroperez@gmail.com',
    phnumber : 3009998877,
    idtype : 'CC',
    idnumber : 998887766,
    money_bank : 'Davivienda',
    money_acc_type : 'Corriente',
    money_acc_number : 9911223344,
  },
  {
    username : '3005554433',
    password : '12345',
    fname : 'Gabriela',
    lname : 'Acevedo',
    email : 'gabace@hotmail.com',
    phnumber : 3005554433,
    idtype : 'CC',
    idnumber : 1111111111,
    money_bank : 'Daviplata',
    money_acc_type : 'Ahorros',
    money_acc_number : 3005554433,
  },
]
